"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭─](bold text)[](surface)$os$username[]\
(fg:surface bg:emerald)$directory[]\
(fg:emerald bg:dark-emerald)$git_branch$git_status[]\
(fg:dark-emerald bg:crimson)$time[ ](fg:crimson)\
$line_break$character"""

palette = 'elwyn_arch'
[palettes.elwyn_arch]
text = "#FFFFFF"
surface = "#434352"
surface_old =  "#313244"
mantle = "#181825"
crimson = "#9e2732"
dark-crimson = "#671921"
dark-silver = "#878787"
silver = "#f8f8f8"
emerald = "#16c299"
dark-emerald = "#0c5040"
gold = "#d7c68f"
dark-gold = "#b79c53"

[os]
disabled = false
style = "bg:surface fg:text"

[os.symbols]
Arch = "󰣇"

[username]
show_always = true
style_user = "bold bg:surface fg:text"
style_root = "bold bg:surface fg:text"
format = '[ $user ]($style)'

[directory]
style = "fg:mantle bold bg:emerald"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙"
"Downloads" = ""
"Music" = "󰝚"
"Pictures" = ""
"Developer" = "󰲋"
"Desktop" = ""
"Duckstation" = "󰇥"
"Videos" = ""
"~" = "󰛓"
"Github" = ""
".dotfiles" = ""

[git_branch]
symbol = ""
style = "bg:dark-emerald"
format = '[[ $symbol ](fg:silver bg:dark-emerald)]($style)'

[git_status]
style = "bg:dark-emerald"
format = '[[($all_status$ahead_behind )](fg:silver bg:dark-emerald)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:peach"
format = '[[ 󰌪 $time ](bold text bg:crimson)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[╰─](bold text)[ ](bold gold)'
error_symbol = '[╰─](bold text)[ ](bold crimson)'
vimcmd_symbol = '[](bold emerald)'
vimcmd_replace_one_symbol = '[](bold fg:gold)'
vimcmd_replace_symbol = '[](bold fg:gold)'
vimcmd_visual_symbol = '[](bold fg:gold)'
